#Requires -Version 5.1
<#
.SYNOPSIS
    Generates WhistleblowerShield Core documentation files.

.DESCRIPTION
    Creates two markdown documentation files in the ./documentation/ directory
    relative to the script's location (intended to be run from the GitHub repo root):

        documentation/ingest-tool-design.md
        documentation/build-json-directive.md

    Safe to re-run — existing files are backed up with a datestamp suffix
    before being overwritten.

.NOTES
    Run from the root of your GitHub repository:
        .\New-WsCoreDocs.ps1

    Requires no external dependencies.

.VERSION
    1.0.0  Initial implementation
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Resolve output directory ──────────────────────────────────────────────────

$repoRoot  = $PSScriptRoot
$outputDir = Join-Path $repoRoot 'documentation'

if ( -not (Test-Path $outputDir) ) {
    New-Item -ItemType Directory -Path $outputDir | Out-Null
    Write-Host "Created directory: $outputDir" -ForegroundColor Green
}

# ── Helper: write file with backup if it already exists ──────────────────────

function Write-DocFile {
    param(
        [string] $FileName,
        [string] $Content
    )

    $filePath = Join-Path $outputDir $FileName

    if ( Test-Path $filePath ) {
        $stamp      = Get-Date -Format 'yyyyMMdd-HHmmss'
        $backupPath = $filePath -replace '\.md$', "-backup-$stamp.md"
        Copy-Item -Path $filePath -Destination $backupPath
        Write-Host "Backed up existing file to: $backupPath" -ForegroundColor Yellow
    }

    Set-Content -Path $filePath -Value $Content -Encoding UTF8
    Write-Host "Written: $filePath" -ForegroundColor Cyan
}


# ══════════════════════════════════════════════════════════════════════════════
# DOCUMENT 1 — ingest-tool-design.md
# ══════════════════════════════════════════════════════════════════════════════

$ingestToolDesign = @'
# Ingest Tool Design

**Project:** WhistleblowerShield Core (`ws-core`)
**File:** `documentation/ingest-tool-design.md`
**Status:** Design specification — implementation pending

---

## Overview

The ingest tool is a PHP-based utility for importing structured legal data
into `ws-core` CPTs from JSON files generated by AI-assisted research (e.g.
Gemini, Claude AI). It is not a one-time migration tool — it is a repeatable,
auditable pipeline designed to run across multiple jurisdictions and data
batches over the life of the project.

The tool is deliberately simple: regex for predictable structures, direct text
writes for prose fields, and a proposed terms log for everything that needs
human review. No complex translation matrix.

---

## JSON File Structure

Every ingest file must contain two top-level keys: `meta` and `records`.

### `meta` block (required)

The `meta` block is read first, before any records are processed. It provides
the run context the ingest tool needs to stamp every record consistently and
to build the proposed terms blacklist before touching any content.

```json
{
  "meta": {
    "source_method":       "ai_assisted",
    "source_name":         "Gemini",
    "jurisdiction_id":     "CA",
    "generated_date":      "2026-03-18",
    "generated_by":        "Gemini 1.5 Pro",
    "record_count":        15,
    "new_terms_proposed": [
      {
        "taxonomy":  "ws_disclosure_type",
        "term":      "Proposed Term Label",
        "notes":     "Gemini's reasoning for why this term was included.",
        "seen_in":   [ "CA-1102.5", "CA-8547" ]
      }
    ]
  },
  "records": []
}
```

### `records` array

An array of statute objects. See `build-json-directive.md` for the full
field schema Gemini is directed to produce.

---

## Processing Pipeline

The ingest tool executes in the following strict sequence:

### Phase 1 — Header parse

1. Read and validate the `meta` block.
2. Load the existing `proposed-terms-log.json` from the documentation directory.
3. Merge any new proposed terms from `meta.new_terms_proposed` into the log,
   appending to `seen_in` arrays for terms already present rather than
   creating duplicates.
4. Build a local blacklist of all proposed term values for use in Phase 3.
5. Save the updated log before processing any records.

### Phase 2 — Pre-flight report

Before processing records, output a summary:

- Total records in batch
- `source_method` and `source_name` that will be stamped on all records
- Count of proposed new terms found in header
- List of proposed terms with taxonomy type and `seen_in` references
- Prompt for confirmation before proceeding (interactive mode only)

### Phase 3 — Record processing

For each record:

1. Create a new WP post of the appropriate CPT (`jx-statute` for statute records).
2. Call `ws_set_source_method( $post_id, WS_SOURCE_AI_ASSISTED )` from header meta.
3. Call `ws_set_source_name( $post_id, $meta['source_name'] )` from header meta.
4. Map each JSON field to its corresponding ACF post meta key (see Field Map below).
5. For array fields (e.g. `disclosure_types`), use `wp_set_object_terms()` for
   taxonomy fields and serialize or repeat for repeater fields.
6. For any field value matching a blacklisted proposed term:
   - Remove the term from the field value entirely.
   - Log the removal: which post, which field, which term was removed.
   - Do NOT write a partial or placeholder value — omit cleanly.
7. After all fields are written, check plain English fields (see below).
8. Set `verification_status` to `unverified` — never `verified` on ingest.

### Phase 4 — Plain English field audit

After each record is written, inspect every plain English eligible field.
If any such field contains text:

- Set `has_plain_english` to `true` on the post.
- Add the post to the plain English review queue.

Output per record:
- Count of plain English fields populated
- List of each populated plain English field by name

Output per batch:
- Total records entering the plain English review queue
- Aggregated list of all affected fields across the batch

### Phase 5 — Post-run report

After all records are processed, write a run report covering:

- Records created successfully
- Records skipped or failed (with reasons)
- Proposed terms removed (post title, field name, term value)
- Plain English queue entries
- Path to updated `proposed-terms-log.json`

---

## Proposed Terms Log

**File:** `documentation/proposed-terms-log.json`

Persistent JSON file maintained across all ingest runs. The ingest tool
reads this file at the start of every run and writes it back after Phase 1
before processing any records.

### Schema

```json
{
  "proposed_terms": [
    {
      "taxonomy":    "ws_disclosure_type",
      "term":        "Proposed Term Label",
      "notes":       "Gemini's reasoning for inclusion.",
      "seen_in":     [ "CA-1102.5", "CA-8547" ],
      "status":      "pending",
      "resolved_on": null,
      "resolution":  null
    }
  ]
}
```

### `status` values

| Value      | Meaning                                              |
|------------|------------------------------------------------------|
| `pending`  | Awaiting human review                                |
| `approved` | Term added to taxonomy — remediation pass needed     |
| `rejected` | Term will not be added — affected records are clean  |
| `mapped`   | Term mapped to an existing taxonomy term             |

### `resolution` field

Free text. When status is set to `approved`, `rejected`, or `mapped`,
record the decision rationale here for future reference.

---

## Field Map — `jx-statute`

| JSON key                              | ACF meta key                  | Type           | Notes                                      |
|---------------------------------------|-------------------------------|----------------|--------------------------------------------|
| `official_name`                       | `post_title`                  | WP core        |                                            |
| `common_name`                         | `ws_common_name`              | text           |                                            |
| `jurisdiction_id`                     | `ws_jurisdiction` taxonomy    | taxonomy       | Map to `ws_jurisdiction` term slug         |
| `legal_basis.statute_citation`        | `ws_statute_citation`         | text           | Tier 1 — legal text, no plain English      |
| `legal_basis.disclosure_types`        | `ws_disclosure_type` taxonomy | taxonomy array | Check against proposed terms blacklist     |
| `legal_basis.protected_class`         | `ws_protected_class`          | text           | Plain English eligible                     |
| `statute_of_limitations.limit_value`  | `ws_sol_value`                | number         |                                            |
| `statute_of_limitations.limit_unit`   | `ws_sol_unit`                 | select         |                                            |
| `statute_of_limitations.trigger`      | `ws_sol_trigger`              | text           | Plain English eligible                     |
| `statute_of_limitations.exhaustion_required` | `ws_exhaustion_required` | true_false  |                                            |
| `statute_of_limitations.exhaustion_details`  | `ws_exhaustion_details`  | textarea    | Plain English eligible                     |
| `statute_of_limitations.tolling_notes`       | `ws_tolling_notes`       | textarea    | Plain English eligible                     |
| `enforcement.primary_agency`          | `ws_primary_agency`           | text           | Plain English eligible                     |
| `enforcement.remedies`                | `ws_remedies`                 | repeater/array | Plain English eligible                     |
| `burden_of_proof.employee_standard`   | `ws_bop_employee`             | text           | Tier 1 — legal text                        |
| `burden_of_proof.employer_defense`    | `ws_bop_employer`             | text           | Tier 1 — legal text                        |
| `burden_of_proof.rebuttable_presumption` | `ws_bop_rebuttable`       | text           | Tier 1 — legal text                        |
| `burden_of_proof_details`             | `ws_bop_details`              | textarea       | Plain English eligible — conditional field |
| `reward_details`                      | `ws_reward_details`           | textarea       | Plain English eligible — conditional field |
| `links.official_url`                  | `ws_official_url`             | url            | Trigger `ws_is_official_link` flag         |
| `links.is_official`                   | `ws_is_official_link`         | true_false     |                                            |

> **Note:** ACF meta key names in this table are indicative. Verify against
> the actual field definitions in `acf-jx-statute.php` before building the
> field map into the ingest tool.

---

## Source Method & Verification Behavior

All ingest records receive:

- `source_method` → value from `meta.source_method` (e.g. `ai_assisted`)
- `source_name`   → value from `meta.source_name` (e.g. `Gemini`)
- `verification_status` → always `unverified` on ingest, regardless of source
- `needs_review`  → `false` on ingest — set manually by admin if needed

Records cannot reach `verification_status = verified` until:
1. `source_name` is populated (always true for ingest records)
2. A human editor manually sets the flag after reviewing the content

The plain English review queue is independent of verification status —
records can be verified before or after plain English review.

---

## Automation vs Interactive Mode

| Mode          | Behavior                                                      |
|---------------|---------------------------------------------------------------|
| Interactive   | Pre-flight report shown, confirmation required before Phase 3 |
| Automated     | Pre-flight report logged to file, processing begins immediately |

Automated mode is appropriate for recurring feed imports (`feed_import`).
Interactive mode is recommended for all first-time batch imports.

---

## Key Architectural Constraints

- **Shortcodes are presentation layer only.** The ingest tool writes directly
  to post meta via WP/ACF APIs — never through shortcodes.
- **`ws_set_source_method()` and `ws_set_source_name()` are immutable.**
  Once written they cannot be overwritten. The ingest tool must call them
  before any subsequent save hooks fire.
- **Proposed terms are removed, not flagged.** The record is written clean.
  The proposed terms log carries the full audit trail of what was removed
  and where.
- **Plain English fields are written as-is from Gemini output.** No
  sanitization beyond standard WP escaping. The plain English review process
  handles quality control downstream.

---

*Last updated: 2026-03-18*
*See also: `build-json-directive.md`, `legal-research-methodology.md`, `project-status.md`*
'@


# ══════════════════════════════════════════════════════════════════════════════
# DOCUMENT 2 — build-json-directive.md
# ══════════════════════════════════════════════════════════════════════════════

$buildJsonDirective = @'
# Build JSON Directive

**Project:** WhistleblowerShield Core (`ws-core`)
**File:** `documentation/build-json-directive.md`
**Purpose:** Verbatim prompt template to issue to Gemini when generating
             structured legal data JSON for ingest into WhistleblowerShield.org.

---

## How to Use This Document

Copy the prompt block below verbatim and paste it to Gemini before providing
the jurisdiction and statute scope. Substitute the bracketed placeholders
before sending. Do not paraphrase or summarize the instructions — Gemini
performs best with the full directive intact.

---

## Prompt Template

---

You are a legal data researcher generating structured JSON for import into a
whistleblower protection legal reference database. Your output must conform
exactly to the schema and rules below. Do not summarize, paraphrase, or
abbreviate these instructions.

### Output format

Produce a single valid JSON object with two top-level keys: `meta` and `records`.

### `meta` block

The `meta` block must appear first and must contain the following keys:

```json
{
  "meta": {
    "source_method":      "ai_assisted",
    "source_name":        "Gemini",
    "jurisdiction_id":    "[TWO-LETTER JURISDICTION CODE, e.g. CA]",
    "generated_date":     "[TODAY'S DATE IN YYYY-MM-DD FORMAT]",
    "generated_by":       "[YOUR MODEL NAME AND VERSION]",
    "record_count":       [INTEGER COUNT OF RECORDS IN THIS BATCH],
    "new_terms_proposed": []
  }
}
```

### `new_terms_proposed` — taxonomy proposals

As you research each statute, you will encounter classification values that
do not fit cleanly into the known taxonomy lists provided below. When this
occurs:

1. Do NOT include the unrecognized term in the record itself.
2. Add an entry to `new_terms_proposed` in the `meta` block.
3. Each entry must follow this exact structure:

```json
{
  "taxonomy":  "[TAXONOMY NAME FROM THE LIST BELOW]",
  "term":      "[YOUR PROPOSED TERM LABEL]",
  "notes":     "[YOUR REASONING FOR WHY THIS TERM IS NEEDED]",
  "seen_in":   [ "[STATUTE IDENTIFIER, e.g. CA-1102.5]" ]
}
```

4. If the same proposed term appears in multiple statutes, list all statute
   identifiers in the `seen_in` array rather than creating duplicate entries.
5. If no new terms are needed, `new_terms_proposed` must be an empty array `[]`.

### Known taxonomy lists

Use only values from these lists when populating taxonomy fields in records.
Any value not present in a list must be proposed via `new_terms_proposed`.

**`disclosure_types`**
- Violation of Law
- Refusal of Illegal Activity
- Internal Reporting
- External Reporting
- Improper Governmental Activity
- Waste
- Fraud
- Abuse of Authority
- Health or Safety Threats
- Unsafe Patient Care
- Facility Conditions
- Quality of Care Grievances
- Environmental Violation
- Financial Fraud
- Securities Violation

**`sol_unit`**
- days
- months
- years

**`protected_class`** *(free text — no fixed taxonomy, populate as found)*

### `records` array

Each record in the `records` array must follow this exact schema. Omit a key
entirely if no data is available — do not use null, empty strings, or
placeholder text.

```json
{
  "jurisdiction_id":  "[TWO-LETTER CODE]",
  "statute_id":       "[JURISDICTION_ID]-[SECTION, e.g. CA-1102.5]",
  "official_name":    "[FULL OFFICIAL STATUTE NAME]",
  "common_name":      "[PLAIN LANGUAGE COMMON NAME IF ONE EXISTS]",

  "legal_basis": {
    "statute_citation":  "[FORMAL CITATION, e.g. Cal. Lab. Code § 1102.5]",
    "disclosure_types":  [ "[FROM KNOWN LIST ONLY]" ],
    "protected_class":   "[WHO IS PROTECTED — free text]"
  },

  "statute_of_limitations": {
    "limit_value":         [INTEGER],
    "limit_unit":          "[days | months | years]",
    "trigger":             "[WHAT EVENT STARTS THE CLOCK]",
    "exhaustion_required": [true | false],
    "exhaustion_details":  "[IF EXHAUSTION REQUIRED, DESCRIBE THE PROCESS]",
    "tolling_notes":       "[ANY TOLLING OR EXTENSION PROVISIONS]"
  },

  "enforcement": {
    "primary_agency": "[AGENCY NAME]",
    "remedies":       [ "[REMEDY DESCRIPTION]" ]
  },

  "burden_of_proof": {
    "employee_standard":      "[LEGAL STANDARD EMPLOYEE MUST MEET]",
    "employer_defense":       "[LEGAL STANDARD FOR EMPLOYER DEFENSE]",
    "rebuttable_presumption": "[IF APPLICABLE — describe the presumption]",
    "burden_of_proof_details_needed": [true | false]
  },

  "reward": {
    "available":       [true | false],
    "reward_details_needed": [true | false]
  },

  "links": {
    "official_url": "[URL TO OFFICIAL GOVERNMENT OR LEGISLATIVE SOURCE]",
    "is_official":  [true | false]
  }
}
```

### Field rules

- **`statute_id`** must be unique within the batch and follow the pattern
  `[JURISDICTION_ID]-[SECTION]`, e.g. `CA-1102.5`.
- **`disclosure_types`** must contain only values from the known taxonomy
  list. Unrecognized values go to `new_terms_proposed`, not here.
- **`exhaustion_details`** must only be present if `exhaustion_required`
  is `true`.
- **`burden_of_proof_details_needed`** set to `true` signals that the
  burden of proof for this statute is complex enough to require a narrative
  explanation field. Set to `false` or omit if the standard fields are
  sufficient.
- **`reward_details_needed`** set to `true` signals that reward provisions
  are present and complex enough to require a narrative explanation field.
- **`is_official`** must be `true` only if the URL points directly to an
  official government, legislative, or regulatory source. Set to `false`
  for secondary sources, legal databases, or aggregators.
- **Do not fabricate data.** If a field value cannot be found through
  research, omit the key entirely.
- **Do not add keys not present in this schema.** Extra keys will be
  ignored by the ingest tool but create noise.

### Scope for this run

Research and generate records for the following:

**Jurisdiction:** [JURISDICTION FULL NAME, e.g. California]
**Jurisdiction ID:** [TWO-LETTER CODE, e.g. CA]
**Scope:** [DESCRIBE WHAT TO COVER, e.g. "All state-level whistleblower
            protection statutes applicable to private sector employees"]
**Exclude:** [ANY STATUTES TO SKIP, or "None"]

Produce the complete JSON object now. Do not include any commentary,
explanation, or markdown outside the JSON block itself.

---

## Notes for the Researcher (not sent to Gemini)

- Verify `record_count` in the header matches the actual number of records
  in the `records` array before running the ingest tool.
- Check `new_terms_proposed` in the header against `proposed-terms-log.json`
  before running ingest — new proposals require a manual review decision
  before affected records can be fully classified.
- The `burden_of_proof_details_needed` and `reward_details_needed` flags
  are signals to you as the researcher — when `true`, plan to author the
  corresponding detail field manually after ingest.
- All non-legalese text fields will enter the plain English review queue
  automatically on ingest. No action needed at import time.
- `source_name` in the meta block should reflect the actual Gemini model
  version used (e.g. "Gemini 1.5 Pro", "Gemini 2.0 Flash") for accurate
  provenance tracking.

---

*Last updated: 2026-03-18*
*See also: `ingest-tool-design.md`, `legal-research-methodology.md`*
'@


# ── Write both files ──────────────────────────────────────────────────────────

Write-DocFile -FileName 'ingest-tool-design.md'   -Content $ingestToolDesign
Write-DocFile -FileName 'build-json-directive.md' -Content $buildJsonDirective

Write-Host ''
Write-Host 'Done. Two documentation files written to ./documentation/' -ForegroundColor Green
Write-Host ''
Write-Host 'Next steps:' -ForegroundColor White
Write-Host '  1. Review both files and adjust ACF meta key names in the field map'
Write-Host '     once acf-jx-statute.php field names are confirmed.'
Write-Host '  2. Create documentation/proposed-terms-log.json as an empty log'
Write-Host '     before running the ingest tool for the first time.'
Write-Host '  3. Add both .md files to version control.'